### ISSUE TITLE
usb descriptor request failed 

### ISSUE THREAD

**Issue by ghost** [Zubax/zubax_babel#2]
Hi , 
I compille the bootloader from the code and find out that when I plug in the USB it can not be recognized because of descriptor request failed .
Then I test the Chibios Demo of STM32F373 USB CDC demo . I works find ,  I have porting the usbcfc.c to repalce the usb_cdc.cpp , It also failed . 
Any help would be appriciate !

**Comment by pavel-kirienko** [comment]
Hi Riz, what hardware did you test the code on?
